services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_DB=shareit
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  # ещё один сервис
  db-init:
    image: postgres:16.1
    container_name: db-init
    # секция для указания зависимостей от других сервисов
    depends_on:
      # указываем, что этот сервис зависит от сервиса с именем db
      db:
        # указываем, что условием запуска будет момент, когда
        # сервис db будет в «здоровом» состоянии
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://shareit:shareit@db:5432/shareit -v ON_ERROR_STOP=1 <<-EOSQL
        DROP TABLE IF EXISTS
        users,
        requests,
        items,
        bookings,
        comments;
        
        CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(512) NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY (id),
        CONSTRAINT qu_user_email UNIQUE (email)
        );

        CREATE TABLE IF NOT EXISTS requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        description VARCHAR(512) NOT NULL,
        created TIMESTAMP WITHOUT TIME ZONE,
        requestor_id BIGINT,
        CONSTRAINT pk_request PRIMARY KEY (id),
        CONSTRAINT fk_requests_users FOREIGN KEY(requestor_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        name VARCHAR(255) NOT NULL,
        description VARCHAR(512) NOT NULL,
        is_available BOOLEAN,
        owner_id BIGINT,
        request_id BIGINT,
        CONSTRAINT fk_items_users FOREIGN KEY(owner_id) REFERENCES users(id),
        CONSTRAINT fk_items_requests FOREIGN KEY(request_id) REFERENCES requests(id),
        CONSTRAINT pk_item PRIMARY KEY (id)
        );

        CREATE TABLE IF NOT EXISTS bookings(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        start_date TIMESTAMP WITHOUT TIME ZONE,
        end_date TIMESTAMP WITHOUT TIME ZONE,
        item_id BIGINT,
        booker_id BIGINT,
        status VARCHAR(16),
        requestor_id BIGINT,
        CONSTRAINT booking_id PRIMARY KEY (id),
        CONSTRAINT fk_bookings_items FOREIGN KEY(item_id) REFERENCES items(id),
        CONSTRAINT fk_bookings_users_booker FOREIGN KEY(booker_id) REFERENCES users(id),
        CONSTRAINT fk_bookings_users_requestor FOREIGN KEY(requestor_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS comments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        text VARCHAR(512) NOT NULL,
        item_id BIGINT,
        author_id BIGINT,
        created TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_comments PRIMARY KEY (id),
        CONSTRAINT fk_comments_users FOREIGN KEY(author_id) REFERENCES users(id),
        CONSTRAINT fk_comments_items FOREIGN KEY(item_id) REFERENCES items(id)
        );
        EOSQL