DROP TABLE IF EXISTS
users,
requests,
items,
bookings,
comments;


CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT qu_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE,
  requestor_id BIGINT,
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT fk_requests_users FOREIGN KEY(requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  is_available BOOLEAN,
  owner_id BIGINT,
  request_id BIGINT,
  CONSTRAINT fk_items_users FOREIGN KEY(owner_id) REFERENCES users(id),
  CONSTRAINT fk_items_requests FOREIGN KEY(request_id) REFERENCES requests(id),
  CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  item_id BIGINT,
  booker_id BIGINT,
  status VARCHAR(16),
  requestor_id BIGINT,
  CONSTRAINT booking_id PRIMARY KEY (id),
  CONSTRAINT fk_bookings_items FOREIGN KEY(item_id) REFERENCES items(id),
  CONSTRAINT fk_bookings_users_booker FOREIGN KEY(booker_id) REFERENCES users(id),
  CONSTRAINT fk_bookings_users_requestor FOREIGN KEY(requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(512) NOT NULL,
  item_id BIGINT,
  author_id BIGINT,
  created TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  CONSTRAINT fk_comments_users FOREIGN KEY(author_id) REFERENCES users(id),
  CONSTRAINT fk_comments_items FOREIGN KEY(item_id) REFERENCES items(id)
);